[project]
name = "deepresearchsdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.13",
    "gradio>=5.34.2",
    "ipykernel>=6.29.5",
    "ipython>=9.3.0",
    "openai-agents>=0.0.19",
]
